@startuml DBOR

title Object Relation - Insurance Use Case

class PersonTable <Nested Table> <<person_obj_table>> {
}

class Pessoa <<pessoa_typ>>{
  +number id
  +string nome
  +number cpf
}

class Corretor <<corretor_typ>> {
  +string corretora
}
class Segurado <<segurado_typ>> {
  +number limite
}

Pessoa --|> Corretor: Herança
Pessoa --|> Segurado: Herança

PersonTable *-- Pessoa
PersonTable *-- Corretor: Sobrecarga
PersonTable *-- Segurado: Sobrecarga

Class Apolice <<apolice_typ>> {
  +number id
  +varray listaItens
  +number valor
  +Segurado segurado
  +Corretor corretor
  +Date dataEfitivação
  +string status
}
Class Proposta <<proposta_typ>> {
  +number valorBoleto
  +Date vencimentoBoleto
}
Class Cotação <<cotacao_typ>> {
  +Date dataCotaçao
}

Class Item <<item_typ>> {
  +Number coordenada
  +string produto
  +number valor
}
Class ItensList <varray, index> <<item_array>>

Class ApoliceTable <Nested Table> <<apolice_obj_table>>

Apolice -- Item
Item --* ItensList

Cotação -up- Proposta
Proposta -up- Apolice

Apolice  -up-* ApoliceTable
Proposta -up-* ApoliceTable
Cotação  -up-* ApoliceTable

@enduml